#!/usr/bin/env php
<?php

// console application

require 'tests/bootstrap.php';

use Rodchyn\ElephantLang\Commands\BuildCommand;
use Rodchyn\ElephantLang\Commands\TestCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new BuildCommand);
$application->add(new TestCommand);
$application->run();
